### ISSUE TITLE
TA assigned: Complete Milestone 4

### ISSUE THREAD

**Issue by parsonsbatsc** [SCCapstone/Treepo#1]
Milestone 4 was due on September 14 at midnight. The information about what is required is at https://cse.sc.edu/capstone/milestone/project-description

Please complete it as soon as possible. Work that is turned in late does have points deducted.

Your group has a project description, but your persona pages are blank.

**Comment by rtankersley** [comment]
We discussed this with Dr. Vidal during our meeting with him last week. He said that once we meet with our client, which we are doing on Tuesday, then we can complete this milestone. He told us that this wouldn't be an issue with the deadline.

**Comment by parsonsbatsc** [comment]
Please speak with him about it, since he told me that all the groups had met with their clients as of last Friday.  He has the final word on grades, so as long as he says it's ok, it's ok.

**Comment by parsonsbatsc** [comment]
Confirmed with Dr. Vidal.  Please make sure this is finished ASAP.

**Comment by rtankersley** [comment]
Thank you for getting that cleared up. Milestone 4 should be complete now.
