### ISSUE TITLE
Trees do not appear in map

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/Treepo#13]
<img width="292" alt="screen shot 2016-12-08 at 2 23 07 pm" src="https://cloud.githubusercontent.com/assets/228704/21024292/e92e21b6-bd51-11e6-91de-729e5c17957e.png">

**Comment by rtankersley** [comment]
I'm not sure what is causing that. It still works on my test phone and the trees are still in the database. I'm guessing it has to be something wrong with the apk itself? I'm not really sure how to fix it because it seems to be working for me, and worked in the demo as well. Any suggestions?

**Comment by josemvidal** [comment]
Nope. I noticed I also don't see the"my location" icon on the map which I think I saw in your demo.

I tested both on the emulator and just now on my phone. Same problem, no trees. You'll have to test more next semester to make sure it works for other people.

**Comment by rtankersley** [comment]
I think the issue is with permissions for location services. I'm guessing since we had the actual code and were plugged in that it didn't need the permissions so we never came across the issue. But are we supposed to fix this for this semester, or just work it out in the spring?

**Comment by josemvidal** [comment]
The M10 deadline is passed so that grade will not change.

Yes, this is a but that will need to get fixed.
