### ISSUE TITLE
Add Tree tour page, instead of menu item

### ISSUE THREAD

**Issue by parsonsbatsc** [SCCapstone/Treepo#34]
I'm a long way away from the start of the tree tour.  Google navigation opened and nicely started giving me driving directions, which were estimated at over half an hour.  You may want to limit the distance, or let the users know the approximate distance to the start of the tour before they enter the navigation screen.

**Comment by josemvidal** [comment]
Add a page with a list of all the tours available, each one says the location where it starts.

Or, another option is to add the tours to the map.
