### ISSUE TITLE
Crashes when user clicks on Share button

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/Treepo#39]
![screenflow](https://cloud.githubusercontent.com/assets/228704/24864894/961ec66e-1dd3-11e7-8714-07c5d8bce894.gif)

**Comment by parsonsbatsc** [comment]
I was able to get this to work on the Galaxy S7 (Android 7) with one of the trees that has an image.  I was not logged in at the time.

**Comment by josemvidal** [comment]
On my phone (Pixel), it sometimes works, other times it crashes.
![screenflow](https://cloud.githubusercontent.com/assets/228704/25098313/0b4c7236-2376-11e7-8547-bfae600e8d5e.gif)
