### ISSUE TITLE
Which Trees have photos?

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/Treepo#40]
Lots of trees, but I can't find the ones with photos. 

Please list the ones that have photos here so we can test.

**Comment by rtankersley** [comment]
Enter these addresses into the search to find the trees that have pictures:
1300 Blossom Street
221 Sumter Street
112 Sumter Street

**Comment by parsonsbatsc** [comment]
Those trees did have photos.  I edited a tree and added a photo, although I'm not sure if this is just saved locally.  It didn't change any other info.

@josemvidal Could you check the one at 1401 Cambridge Lane, and see if the photo looks like an admittedly bad photo of one of my dogs?

**Comment by josemvidal** [comment]
It checks out, closing.

<img width="424" alt="android_emulator_-_pixel_api_25_5554" src="https://cloud.githubusercontent.com/assets/228704/25097780/ebada794-2373-11e7-8320-b08ab89bf71c.png">
