### ISSUE TITLE
Release your code?

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/Treepo#51]
I was just contacted by Elizabeth Marks. She has been trying to contact you and has failed to.

She wants to continue developing the app. Would you be interested? Or, would you be willing to release the code in this repo under an open-source license (say MIT License)?

**Comment by josemvidal** [comment]
She says that

> They told me it was open code (we agreed to that as well), and they were very proud that it could benefit others, but we have no way of accessing it.
Thank you for helping us with this.

But, I cannot give her access to this repo without your permission.

I told her:

> I am afraid I cannot give you access to their code without their permission.
>
> They have to tell me that they want me to give you a copy of their code. It is USC policy. It is the same as if it was a student’s old tests, homeworks, papers, etc.

**Comment by rtankersley** [comment]
How do we go about giving them access to this repository or even just the code itself? I have been in contact with Elizabeth and am working to give them the ability to work on this app themselves, but I wasn't sure if I should make this repository public or what the best solution would be.

**Comment by josemvidal** [comment]
You can make this repo public by clicking on Settings -> Make this repository public. Once you do, anyone can clone it.

Before you do that you should add a LICENSE.txt file. You can [find some here](https://choosealicense.com/) I recommend the MIT License. Mostly, these protect you from getting sued and require everyone who uses your code to mention your name in their license. You can  add files to your repo from github itself ("create new file" button).

Or, if you want just Elizabeth to get read permission then you can add her as a collaborator in Settings->Collaborators
